services:
  db:
    image: mysql:8.0.27
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: keyhint
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - sam-network

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=mysql
    ports:
      - "3001:80"
    networks:
      - sam-network

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - sam-network

networks:
  sam-network:
